version: "3.8"

services:
  backend-flask:
    environment:
      - FRONTEND_URL:"https://3000-ahmedlekan-awsbootcampc-8gz6szkbm46.ws-us117.gitpod.io"
      - BACKEND_URL:"https://4567-ahmedlekan-awsbootcampc-8gz6szkbm46.ws-us117.gitpod.io"
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
    command: python3 -m flask run --host=0.0.0.0 --port=4567

  frontend:
    environment:
      - REACT_APP_BACKEND_URL:"https://4567-ahmedlekan-awsbootcampc-8gz6szkbm46.ws-us117.gitpod.io"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
    command: sh -c "npm install && npm start"

networks:
  internal-network:
    driver: bridge
    name: cruddur