version: "3.8"

services:
  backend-flask:
    environment:
      - FRONTEND_URL=https://3000-ahmedlekan-awsbootcampc-mkbruxb3sox.ws-us118.gitpod.io
      - BACKEND_URL=https://4567-ahmedlekan-awsbootcampc-mkbruxb3sox.ws-us118.gitpod.io
      - AWS_XRAY_URL= "*4567-ahmedlekan-awsbootcampc-mkbruxb3sox.ws-us118.gitpod.io"
      - AWS_XRAY_DAEMON_ADDRESS = "xray_daemon:2000" 
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
    command: python3 -m flask run --host=0.0.0.0 --port=4567
    depends_on:
      - postgres
      - dynamodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    environment:
    - REACT_APP_BACKEND_URL=https://4567-ahmedlekan-awsbootcampc-mkbruxb3sox.ws-us118.gitpod.io 
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
    command: npm start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  dynamodb:
    user: root
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    networks:
      - internal-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  xray-daemon:
    image: amazon/aws-xray-daemon
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: us-east-1
    command:
      - "xray -o -b xray-daemon:2000"
    ports:
    - "2000:2000/udp"

volumes:
  postgres_data:
  dynamodb_data:

networks:
  internal-network:
    driver: bridge
    name: cruddur